### ISSUE TITLE
Pymux doesn't honor $SHELL

### ISSUE THREAD

**Issue by kseistrup** [jonathanslenders/pymux#10]
How does `pymux` decide which shell to start? It doesn't seem to honor the `SHELL` environment variable:

```sh
$ echo $SHELL
/usr/bin/xonsh
$ 1+2
3
$ exec pymux
$ echo $SHELL
/usr/bin/xonsh
$ 1+2
bash: 1+2: command not found
$ 
```

**Comment by jonathanslenders** [comment]
Hi @kseistrup,

This is the code: https://github.com/jonathanslenders/pymux/blob/master/pymux/utils.py#L164
```python
username = getpass.getuser()
shell = pwd.getpwnam(username).pw_shell
```

I'll take $SHELL into account.
Jonathan

**Comment by kseistrup** [comment]
Thanks, I just found the `get_default_shell()` method.

Perhaps something like
```py
def get_current_shell():
    """
    Return the user's current shell.
    """
    return os.environ.get('SHELL', get_default_shell())
```
could work.

**Comment by jonathanslenders** [comment]
Fixed in: https://github.com/jonathanslenders/pymux/commit/d016782a44a39a1b9b4b75c06028953ba35b9afe

Thanks a lot for reporting this issue!

**Comment by kseistrup** [comment]
Nice, thanks! :smile:

**Comment by jonathanslenders** [comment]
A new release has been pushed to Pypi. Could you try again?

**Comment by kseistrup** [comment]
I `pip` installed from the git repos and it works like a charm.
