### ISSUE TITLE
closing a pane does not go to previous pane

### ISSUE THREAD

**Issue by atsepkov** [jonathanslenders/pymux#14]
Actions performed:

- split pane (orientation doesn't matter)
- split pane again
- close pane (I used `exit`)

Expected result (as in tmux):

- Focus goes back to previously active pane (in this case pane 1)

Actual result:

- Focus goes back to very first pane (pane 0)

Not so much of a bug but a convenience for saner flow.

**Comment by jonathanslenders** [comment]
Fixed in: https://github.com/jonathanslenders/pymux/commit/6b40ace613d196b264acb3882244e79d033b2502
