### ISSUE TITLE
Double Exec?

### ISSUE THREAD

**Issue by odeits** [jonathanslenders/pymux#17]
Line 102 of process.py

```
def execv():
    if before_exec_func:
        before_exec_func()

    for p in os.environ['PATH'].split(':'):
        path = os.path.join(p, command[0])
        if os.path.exists(path) and os.access(path, os.X_OK):
            os.execv(path, command)
```

Should this not return the `os.execv`? it seems like it will call it for multiple hits in the path.

**Comment by aarya123** [comment]
os.execv(), from my understanding, takes over the process (in this case, tmux) and won't return
https://docs.python.org/2/library/os.html#os.execv

**Comment by odeits** [comment]
You are correct. Closing
