### ISSUE TITLE
Can't copy paste using third button in Linux

### ISSUE THREAD

**Issue by rapha8l** [jonathanslenders/pymux#37]
Hi, 
Tested on two  different systems, selecting text and copying using third button doesn't work
Thanks !

**Comment by eas604** [comment]
You may need to hold <kbd>Shift</kbd> when clicking for it to pass through to the terminal emulator. That's what I do with `gnome-terminal`.

**Comment by rapha8l** [comment]
Thanks, in fact it works, though it the first program that needs using "shift" for third button copy

**Comment by jonathanslenders** [comment]
The reason for this is that pymux requests the terminal to receive mouse events. That way we can for instance select panes on click. If you prefer not to have mouse support in pymux itself, that is possible by running the follow command in the <kbd>Ctrl-B</kbd><kbd>:</kbd> prompt:
``set mouse off``. Does it work that way?

**Comment by rapha8l** [comment]
Hi,

Thanks, indeed set mouse off works
I also wanted to try ^B page up to scroll up (like in Tmux) but it doesn't work. Is there another way to do this ?
Could it be possible to have a little doc with all options available ?
And just a last thing as I'm here :-) , maybe it'd be cleaner (on Linux/*BSD) to have the configuration located in $HOME/.config/pymux/ ?
Thanks again !

**Comment by jonathanslenders** [comment]
The ``^B page up`` key binding has been added.

(It goes in copy-mode, but doesn't yet do the page-up part. Press page-up again to go up. I need some changes in prompt-toolkit first in order to do the last part in a clean way.)

**Comment by rapha8l** [comment]
Works great, thanks a lot
