### ISSUE TITLE
Binding Ctrl-h to some action prevent backspace to be working fine

### ISSUE THREAD

**Issue by jczulian** [jonathanslenders/pymux#50]
In my config file I have Ctrl-h bound to the previous-window command. Unfortunately having this setting makes also the backspace key triggering this command. This behavior prevent me to actually using backspace for what it is meant for.

You mention that ctrl-h and backspace are somehow the same key sequence. However in tmux I do have the similar setting and it works. So it might be possible to have pymux override this default behavior and adopting something similar to what tmux does.

Here is an excerpt from my config file
```
bind-key -n C-l next-window
bind-key -n C-h previous-window
```

**Comment by jonathanslenders** [comment]
Hi @jczulian,

I just fixed the issue in this commit of prompt-toolkit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/b586e477c374a78dd1808ac9818ea6be60b87ccc

If you have time, can you try to checkout the latest master branch of prompt-toolkit, install that and try again. If it doesn't work, we'll see tomorrow.

Cheers,
Jonathan

**Comment by jczulian** [comment]
Hi @jonathanslenders,

I have just tried it, works perfectly. Thank you very much, I can now get back to using pymux instead of using tmux.

Keep the good work and thanks a million for your help.
