### ISSUE TITLE
Auto-update status bar

### ISSUE THREAD

**Issue by deeplook** [jonathanslenders/pymux#52]
It seems like the lower status bar gets updated only when the user is typing into the terminal or clicks the mouse inside. So when it shows e.g. the current time this can be at least misleading. I've just checked, tmux does perform an auto-update.

Now turning this into a feature request: ideally it would be very useful to have hooks implemented as simple functions by the user, referenced by name/location from the config file that return arbitrary strings to be shown in the lower status bar. If these would be called in some regular, configurable interval, then that would be a very useful way of showing one or more values that change over time, like a timestamp, a directory file size, or anything else.

**Comment by jonathanslenders** [comment]
Hi @deeplook,
Thanks for creating this issue. I think for tmux, the command is ``tmux set status-interval 1``. I propose that I will implement the same option, in order to stay compatible with tmux. Would that work for you?

**Comment by deeplook** [comment]
@jonathanslenders If that works, fine with me. I'm not that much of a tmux/pymux power user. I noticed this buglet because I'd like to see some other crazy stuff (too big for a feature request) that I should better suggest to you directly by email (?).

**Comment by jonathanslenders** [comment]
Hi @deeplook, this has been implemented in this commit: https://github.com/jonathanslenders/pymux/commit/2d62bb360c935364c594467be5625011a93a8868 (check out the master branch.)
Feel free to contact me directly by email for anything. (Find my address on my GitHub account page.)
