### ISSUE TITLE
No Pane Tilebars?

### ISSUE THREAD

**Issue by PodioSpaz** [jonathanslenders/pymux#56]
Hello,

None of my panes have a titlebar.  Am I missing a configuration setting?

Thanks

**Comment by jonathanslenders** [comment]
Hi @PodioSpaz,

Yes, in the latest version, I turned them off by default, just like tmux.
Do ``Ctrl-B  : (colon)`` to go in command mode. Then type ``set-option pane-border-status on``.
Let me know if that doesn't work.

**Comment by PodioSpaz** [comment]
Hello @jonathanslenders,

That worked. Thanks.
