### ISSUE TITLE
Library support?

### ISSUE THREAD

**Issue by dothebart** [jonathanslenders/pymux#61]
You mention in the readme that you may create a library from pymux. How far in the future is that plan?
I'm currently working on a shell ui for jenkins:
https://github.com/dothebart/jsh
and would need something to have parallel builds browseable in a smart way - like a multi window less. 
The copy buffer is mentioned to be searcheable with hilighting - can it als work / tail a file?

**Comment by jonathanslenders** [comment]
Hi Wilfried, there are still a few things that need to be done for this to work.
I'm working on some refactoring of the prompt_toolkit internal architecture. Right now, it's difficult to make parts of pymux reusable for other applications. But that's going to be fixed. (Giving a deadline is hard, but I hope to finish that part in the coming 6 months.) Then I need to rewrite parts of pymux and pyvim to work with the new prompt_toolkit API.
Doing a tail on a file is technically possible. Have a look at pypager: https://github.com/jonathanslenders/pypager  So to summarize. All of this in not really easy right now, but I hope it becomes easy and fun in the near future.

**Comment by dothebart** [comment]
Thanks a lot, so maybe it will become an option in the future. Thanks for the hint.
