### ISSUE TITLE
Does this tool work?

### ISSUE THREAD

**Issue by trungphan** [jonathanslenders/pymux#66]
It never seems to work for me.
I install it with: pip install pymux
then: pymux
and the cursor just jumps to the top.

**Comment by jonathanslenders** [comment]
Hi @trungphan,

Can you test the latest version of the "master" branch? There was an issue regarding compatibility with the latest Pyte version.

**Comment by trungphan** [comment]
OK, thanks. With the sources, I do: python setup.py install and it seems to work
